export const SET_IS_LOADING = 'SET_IS_LOADING';
export const ON_SUCCESS = 'ON_SUCCESS';
export const ON_ERROR = 'ON_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_AFTER_FETCHING =
  'SET_CURRENT_USER_AFTER_FETCHING';
export const SIGN_OUT = 'SIGN_OUT';
