export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CHECKED = 'SET_CHECKED';
export const SET_SHOW_REQUESTS = 'SET_SHOW_REQUESTS';
export const SET_REQUEST_SENDERS = 'SET_REQUEST_SENDERS';
export const SET_REQUEST_SENDERS_AFTER_LOADING =
  'SET_REQUEST_SENDERS_AFTER_LOADING';
export const REMOVE_REQUEST_SENDER = 'REMOVE_REQUEST_SENDER';
