export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CHECKED = 'SET_CHECKED';
export const SET_SHOW_REQUESTS = 'SET_SHOW_REQUESTS';
export const SET_FOLLOW_REQUESTS = 'SET_FOLLOW_REQUESTS';
export const ON_HIDDEN = 'ON_HIDDEN';
