export const TOGGLE_IS_SAVED_AFTER_LOADING = 'TOGGLE_IS_SAVED_AFTER_LOADING';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const SET_IS_LIKE_BUTTON_LOADING = 'SET_IS_LIKE_BUTTON_LOADING';
export const SET_IS_SAVE_BUTTON_LOADING = 'SET_IS_SAVE_BUTTON_LOADING';
