export const SET_IS_CONFIRM_BUTTON_LOADING = 'SET_IS_CONFIRM_BUTTON_LOADING';
export const SET_IS_DELETE_BUTTON_LOADING = 'SET_IS_DELETE_BUTTON_LOADING';
export const SET_IS_FOLLOW_BUTTON_LOADING = 'SET_IS_FOLLOW_BUTTON_LOADING';
export const TOGGLE_IS_CONFIRMED_AFTER_LOADING =
  'TOGGLE_IS_CONFIRMED_AFTER_LOADING';
export const TOGGLE_IS_FOLLOWING_AFTER_LOADING =
  'TOGGLE_IS_FOLLOWING_AFTER_LOADING';
