export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SAVED_POSTS_AFTER_LOADING = 'SET_SAVED_POSTS_AFTER_LOADING';
export const SET_SAVED_POSTS_AFTER_ADDING = 'SET_SAVED_POSTS_AFTER_ADDING';
export const SET_SAVED_POSTS_AFTER_REMOVING = 'SET_SAVED_POSTS_AFTER_REMOVING';
