export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SAVE_POST = 'SAVE_POST';
export const UNSAVE_POST = 'UNSAVE_POST';
export const SET_SAVED_POSTS_AFTER_FETCHING = 'SET_SAVED_POSTS_AFTER_FETCHING';
