export const SET_IS_OPEN = 'SET_IS_OPEN';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_FILTERED_USERS_AFTER_FETCHING =
  'SET_FILTERED_USERS_AFTER_FETCHING';
export const OPEN_FIRST_TIME = 'OPEN_FIRST_TIME';
