export const SET_IS_OPEN = 'SET_IS_OPEN';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SEARCH_HISTORY_AFTER_LOADING =
  'SET_SEARCH_HISTORY_AFTER_LOADING';
export const SET_SEARCH_HISTORY_AFTER_ADDING =
  'SET_SEARCH_HISTORY_AFTER_ADDING';
export const SET_SEARCH_HISTORY_AFTER_REMOVING =
  'SET_SEARCH_HISTORY_AFTER_REMOVING';
export const SET_SEARCH_HISTORY_AFTER_REMOVING_ALL =
  'SET_SEARCH_HISTORY_AFTER_REMOVING_ALL';
export const SET_FILTERED_USERS = 'SET_FILTERED_USERS';
export const OPEN_FIRST_TIME = 'OPEN_FIRST_TIME';
