export const SET_IS_OPEN = 'SET_IS_OPEN';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SEARCH_HISTORY_AFTER_LOADING =
  'SET_SEARCH_HISTORY_AFTER_LOADING';
export const ADD_SEARCH_HISTORY_ITEM = 'ADD_SEARCH_HISTORY_ITEM';
export const UPDATE_SEARCH_HISTORY_ITEM_CREATED_AT =
  'UPDATE_SEARCH_HISTORY_ITEM_CREATED_AT';
export const SET_SEARCH_HISTORY_AFTER_REMOVING =
  'SET_SEARCH_HISTORY_AFTER_REMOVING';
export const SET_SEARCH_HISTORY_AFTER_REMOVING_ALL =
  'SET_SEARCH_HISTORY_AFTER_REMOVING_ALL';
export const SET_FILTERED_USERS = 'SET_FILTERED_USERS';
export const OPEN_FIRST_TIME = 'OPEN_FIRST_TIME';
